project:
  type: website
  output-dir: docs
  
website:
  title: "sCORE Seedling Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cerulean
    toc: true

editor: source

